MAX_DURATION = 7200
MAX_STEPS_PER_EPISODE = 200
BATCH_SIZE = 64
GAMMA = 0.95
UPDATE_TARGET_EVERY = 50
LEARNING_RATE = 1e-3
STATE_DIM_OBSTACLE = 8
STATE_DIM_BALL = 2
ACTION_DIM = 7
MODEL_PATH = 'dqn_model.pth'
REWARDS_PATH = 'episode_rewards.npy'
PLOT_PATH = 'training_plot.png'

EPSILON_START = 1.0
EPSILON_END = 0.1
EPSILON_DECAY = 0.96

MAX_EPISODES = 120
MAX_STEPS_WITHOUT_BALL = 20
REWARD_WINDOW_SIZE = 10
TARGET_REWARD = 400