MAX_DURATION = 7200
MAX_STEPS_PER_EPISODE = 100
BATCH_SIZE = 64
GAMMA = 0.9
UPDATE_TARGET_EVERY = 100
LEARNING_RATE = 1e-3
STATE_DIM_OBSTACLE = 8
STATE_DIM_BALL = 2
ACTION_DIM = 8
MODEL_PATH = '../python/dqn_model1.pth'
REWARDS_PATH = '../python/episode_rewards.npy'
PLOT_PATH = 'training_plot.png'

EPSILON_START = 1.0
EPSILON_END = 0.05
EPSILON_DECAY = 0.97